2021-06-24 06:16:05|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:16:05|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:16:34|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:16:34|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:16:34|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:16:34|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:16:37|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:16:37|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:16:37|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:16:37|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:17:06|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:17:06|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:17:06|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:17:06|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:17:09|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:17:09|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:17:09|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:17:09|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:17:27|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:17:27|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:17:28|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:17:28|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:17:31|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:17:31|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:17:31|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:17:31|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:18:04|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:18:04|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:18:04|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:18:04|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:18:07|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:18:07|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:18:07|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:18:07|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:23:28|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:23:28|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:23:29|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:23:29|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:23:31|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:23:31|   DEBUG|testAction.py[:58]|1234561
2021-06-24 06:23:32|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:23:32|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:23:34|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:23:34|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:23:35|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:23:35|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:24:04|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:24:04|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:24:05|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:24:05|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:24:07|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:24:07|   DEBUG|testAction.py[:58]|1234561
2021-06-24 06:24:08|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:24:08|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:24:11|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:24:11|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:24:11|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:24:11|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:25:03|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:25:03|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:25:03|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:25:03|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:25:06|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:25:06|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:25:06|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:25:06|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:25:09|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:25:09|   DEBUG|testAction.py[:58]|1234561
2021-06-24 06:25:09|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:25:09|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:25:52|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:25:52|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:25:52|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:25:52|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:25:55|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:25:55|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:25:55|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:25:55|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:25:58|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:25:58|   DEBUG|testAction.py[:58]|1234561
2021-06-24 06:25:58|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:25:58|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:28:36|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:28:36|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:28:36|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-24 06:28:36|    INFO|testAction.py[:105]|载入主页面...
2021-06-24 06:28:39|   DEBUG|testAction.py[:57]|admin1
2021-06-24 06:28:39|   DEBUG|testAction.py[:58]|123456
2021-06-24 06:28:39|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:28:39|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-24 06:28:42|   DEBUG|testAction.py[:57]|admin
2021-06-24 06:28:42|   DEBUG|testAction.py[:58]|1234561
2021-06-24 06:28:42|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-24 06:28:42|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:02:58|   DEBUG|testAction.py[:57]|sniper
2021-06-25 15:02:58|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:02:59|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:02:59|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:03:26|   DEBUG|proactor_events.py[:623]|Using proactor: IocpProactor
2021-06-25 15:03:59|    INFO|testAction.py[:99]|response json: {'code': 0}
2021-06-25 15:03:59| WARNING|log.py[:224]|Not Found: /favicon.ico
2021-06-25 15:04:26|   DEBUG|testAction.py[:57]|sniper
2021-06-25 15:04:26|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:04:27|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:04:27|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:10:23|   DEBUG|testAction.py[:57]|admin1
2021-06-25 15:10:23|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:10:23|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:10:23|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:10:26|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:10:26|   DEBUG|testAction.py[:58]|1234561
2021-06-25 15:10:26|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:10:26|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:19:19|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:19:19|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:19:19|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:19:19|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:19:22|   DEBUG|testAction.py[:57]|pingshi-bi
2021-06-25 15:19:22|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:19:22|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:19:22|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:19:50|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:19:50|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:19:51|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:19:51|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:19:54|   DEBUG|testAction.py[:57]|pingshi-bi
2021-06-25 15:19:54|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:19:54|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:19:54|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:20:12|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:20:12|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:20:12|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:20:12|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:20:15|   DEBUG|testAction.py[:57]|sniper
2021-06-25 15:20:15|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:20:15|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:20:15|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:29:26|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:29:26|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:29:26|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:29:26|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:29:29|   DEBUG|testAction.py[:57]|sniper
2021-06-25 15:29:29|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:29:29|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:29:29|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:33:39|   DEBUG|testAction.py[:57]|admin1
2021-06-25 15:33:39|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:33:40|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:33:40|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:33:56|   DEBUG|testAction.py[:57]|sniper1
2021-06-25 15:33:56|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:33:56|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:33:56|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:34:48|   DEBUG|testAction.py[:57]|admin1
2021-06-25 15:34:48|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:34:48|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:34:48|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:35:23|   DEBUG|testAction.py[:57]|sniper1
2021-06-25 15:35:23|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:35:24|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 15:35:24|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 15:37:46|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:37:46|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:37:46|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:37:46|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:37:52|   DEBUG|testAction.py[:57]|sniper
2021-06-25 15:37:52|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:37:53|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:37:53|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:38:48|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:38:48|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:38:49|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:38:49|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:38:55|   DEBUG|testAction.py[:57]|sniper
2021-06-25 15:38:55|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:38:55|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:38:55|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:39:34|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:39:34|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:39:34|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:39:34|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:39:40|   DEBUG|testAction.py[:57]|sniper
2021-06-25 15:39:40|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:39:41|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:39:41|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:39:47|   DEBUG|testAction.py[:57]|admin
2021-06-25 15:39:47|   DEBUG|testAction.py[:58]|123456
2021-06-25 15:39:47|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:39:47|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 15:40:22|   DEBUG|testAction.py[:57]|sniper
2021-06-25 15:40:22|   DEBUG|testAction.py[:58]|111111
2021-06-25 15:40:22|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 15:40:22|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 21:22:24|   DEBUG|testAction.py[:57]|admin
2021-06-25 21:22:24|   DEBUG|testAction.py[:58]|123456
2021-06-25 21:22:24|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 21:22:24|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 21:22:29|   DEBUG|testAction.py[:57]|sniper
2021-06-25 21:22:29|   DEBUG|testAction.py[:58]|111111
2021-06-25 21:22:30|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 21:22:30|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 21:22:35|   DEBUG|testAction.py[:57]|admin
2021-06-25 21:22:35|   DEBUG|testAction.py[:58]|123456
2021-06-25 21:22:36|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 21:22:36|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 21:22:51|   DEBUG|testAction.py[:57]|sniper
2021-06-25 21:22:51|   DEBUG|testAction.py[:58]|111111
2021-06-25 21:22:51|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 21:22:51|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 21:25:35|   DEBUG|testAction.py[:57]|admin
2021-06-25 21:25:35|   DEBUG|testAction.py[:58]|123456
2021-06-25 21:25:35|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 21:25:35|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 21:25:41|   DEBUG|testAction.py[:57]|sniper
2021-06-25 21:25:41|   DEBUG|testAction.py[:58]|111111
2021-06-25 21:25:41|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-25 21:25:41|    INFO|testAction.py[:105]|载入主页面...
2021-06-25 21:25:47|   DEBUG|testAction.py[:57]|admin1
2021-06-25 21:25:47|   DEBUG|testAction.py[:58]|123456
2021-06-25 21:25:47|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2021-06-25 21:25:47|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2021-06-25 21:25:53|   DEBUG|testAction.py[:57]|sniper1
