2021-06-26 07:28:44|   ERROR|testAction.py[:95]|(1062, "Duplicate entry 'sniper' for key 'username'")
Traceback (most recent call last):
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'sniper' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 92, in addUser
    User.objects.create_superuser(username='sniper', password='111111', email='111111@qq.com')
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\contrib\auth\models.py", line 163, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\contrib\auth\models.py", line 146, in _create_user
    user.save(using=self._db)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\contrib\auth\base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'sniper' for key 'username'")
2021-06-26 07:28:44|    INFO|testAction.py[:99]|response json: {'code': -1, 'msg': '(1062, "Duplicate entry \'sniper\' for key \'username\'")'}
2021-06-26 07:28:44| WARNING|log.py[:224]|Not Found: /favicon.ico
2021-06-26 07:28:52| WARNING|log.py[:224]|Not Found: /loginr/
2021-06-26 07:29:03|   DEBUG|testAction.py[:57]|admin
2021-06-26 07:29:03|   DEBUG|testAction.py[:58]|123456
2021-06-26 07:29:03|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-26 07:29:03|    INFO|testAction.py[:105]|载入主页面...
2021-06-26 07:29:46|   DEBUG|testAction.py[:57]|admin
2021-06-26 07:29:46|   DEBUG|testAction.py[:58]|123456
2021-06-26 07:29:46|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-26 07:29:46|    INFO|testAction.py[:105]|载入主页面...
2021-06-26 07:29:51|    INFO|testAction.py[:105]|载入主页面...
2021-06-26 07:29:53|   ERROR|testAction.py[:146]|日期不在允许范围内
Traceback (most recent call last):
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 129, in orderAddCommit
    raise Exception("日期不在允许范围内")
Exception: 日期不在允许范围内
2021-06-26 07:29:53|    INFO|testAction.py[:105]|载入主页面...
2021-06-26 07:29:58|    INFO|testAction.py[:105]|载入主页面...
2021-06-26 07:30:16|   DEBUG|testAction.py[:57]|admin
2021-06-26 07:30:16|   DEBUG|testAction.py[:58]|123456
2021-06-26 07:30:17|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-26 07:30:17|    INFO|testAction.py[:105]|载入主页面...
2021-06-26 07:30:21|    INFO|testAction.py[:105]|载入主页面...
2021-06-26 07:30:25|    INFO|testAction.py[:105]|载入主页面...
2021-06-26 07:30:30|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:13:14|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:13:14|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:13:14|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:13:14|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:13:15|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:20:56|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:20:56|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:20:57|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:20:57|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:20:58|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:30:52|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:30:52|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:30:52|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:30:52|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:30:54|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:32:36|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:32:36|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:32:36|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:32:36|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:32:41|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:37:43|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:37:43|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:37:43|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:37:43|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:37:44|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:38:30|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:38:30|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:38:30|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:38:30|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:38:32|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:40:08|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:40:08|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:40:08|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:40:08|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:40:09|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:40:35|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:40:35|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:40:35|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:40:35|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:40:36|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:40:46|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:40:46|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:40:46|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:40:46|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:40:51|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:45:53|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:45:53|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:45:53|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:45:53|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:48:38|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:48:38|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:48:39|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:48:39|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:48:43|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:48:48|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:48:52|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:48:57|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:49:01|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:49:05|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:49:10|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:49:15|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:49:19|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:49:23|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:49:28|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:18|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:53:18|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:53:18|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:53:18|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:24|   DEBUG|testAction.py[:57]|sniper
2021-06-27 09:53:24|   DEBUG|testAction.py[:58]|111111
2021-06-27 09:53:24|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:53:24|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:30|   DEBUG|testAction.py[:57]|admin
2021-06-27 09:53:30|   DEBUG|testAction.py[:58]|123456
2021-06-27 09:53:30|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 09:53:30|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:34|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:39|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:43|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:48|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:52|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:53:57|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:54:01|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:54:06|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:54:10|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:54:14|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 09:54:19|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:19:38|   DEBUG|testAction.py[:57]|admin
2021-06-27 10:19:38|   DEBUG|testAction.py[:58]|123456
2021-06-27 10:19:38|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 10:19:38|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:19:43|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:19:47|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:19:51|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:19:56|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:00|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:04|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:09|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:13|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:18|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:22|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:26|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:30|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:20:34|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:21:34|   DEBUG|testAction.py[:57]|admin
2021-06-27 10:21:34|   DEBUG|testAction.py[:58]|123456
2021-06-27 10:21:34|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 10:21:34|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:21:38|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:21:43|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:22:04|   DEBUG|testAction.py[:57]|admin
2021-06-27 10:22:04|   DEBUG|testAction.py[:58]|123456
2021-06-27 10:22:04|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 10:22:05|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:22:08|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:22:12|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:23:09|   DEBUG|testAction.py[:57]|admin
2021-06-27 10:23:09|   DEBUG|testAction.py[:58]|123456
2021-06-27 10:23:09|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 10:23:09|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:23:13|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:23:17|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:26:02|   DEBUG|testAction.py[:57]|admin
2021-06-27 10:26:02|   DEBUG|testAction.py[:58]|123456
2021-06-27 10:26:03|    INFO|testAction.py[:78]|response json: {'code': 0}
2021-06-27 10:26:03|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:26:08|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:26:13|    INFO|testAction.py[:105]|载入主页面...
2021-06-27 10:26:14|    INFO|testAction.py[:105]|载入主页面...
2021-06-28 09:15:30|   ERROR|log.py[:224]|Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86180\Desktop\测试\testProject\testProject\testAction.py", line 40, in login
    raise SystemError("method error: post")
SystemError: method error: post
